### PR TITLE
Use Github Actions for testing

### PR DESCRIPTION
**Pull request by gitetsu**
Hi!
This PR allows using Kahlan 5.x and PHP 8.x.
(I know this package is named Kahlan**4**, but I'd like to use this under 5.x and PHP 8 😃 )

Also, this uses Github Actions instead of Travis CI for easy multiple versions testing.
For the test results, please refer to [my repository](https://github.com/gitetsu/laravel-kahlan4/actions/runs/1028933624).
Because [Kahlan 5.x is not compatible with PHP 7.x](https://github.com/kahlan/kahlan/issues/381#issuecomment-824337448) and [Laravel 8.x requires PHP ^7.3](https://github.com/laravel/framework/blob/8.x/composer.json#L18), this excludes the tests for that combinations.

What's your take on this?

### CODE REVIEW

**Comment by midnightSuyama** [comment]
@gitetsu
LGTM! Sorry for my late reply.
I'm going to change the meaning of “4” in the package name to 4 or more.

**Comment by gitetsu** [comment]
Thanks for the review!

I would be grateful if you could add a new tag when you have time.

**Comment by gitetsu** [comment]
@midnightSuyama 
Would it be possible for you to merge this and release a new version? 🙇

**Comment by midnightSuyama** [comment]
@gitetsu
Thank you for reminding me. Released 2.0.0.

**Pull request merged**
